title: Scholar
author:
  name: Konstantinos Chorianopoulos
  email: choko@ionio.gr
description: > #
    Papers by Konstantinos Chorianopoulos 
    with PDF download and publisher links. 
    Research in the areas of  user interfaces, 
    software studies, intelligence augmentation.

header_pages:
  - readme.markdown

minima:
  social_links:
    rss: rss
    github: epidrome

# Build settings
theme: minima 

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-scholar

scholar:
    style: acm-siggraph
    locale: en
    sort_by: year
    order: descending
    group_by: none
    group_order: ascending
    bibliography_list_tag: ul
    bibliography_template: entry
    details_dir: "/" 
    details_layout: details.html
    details_link: ""
    repository: "https://pdf.epidro.me"

